/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package firebase.database;

import com.google.firebase.database.FirebaseDatabase;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;


@Kroll.module(name = "FirebaseDatabase", id = "firebase.database")
public class FirebaseDatabaseModule extends KrollModule {

    FirebaseDatabase database;

    // You can define constants with @Kroll.constant, for example:
    // @Kroll.constant public static final String EXTERNAL_NAME = value;

    public FirebaseDatabaseModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

    @Kroll.method
    public DatabaseReferenceProxy getReference(@Kroll.argument(optional = true) KrollDict kd) {
        database = FirebaseDatabase.getInstance();
        String path = "";
        if (kd.containsKeyAndNotNull("path")) {
            path = kd.getString("path");
        }
        DatabaseReferenceProxy drp = new DatabaseReferenceProxy(database.getReference(path));
        return drp;
    }


    @Kroll.getProperty
    public Long getFirebaseServerTimestamp() {
        return System.currentTimeMillis() / 1000L;
    }

}

